import { Vehicle } from "../models/models";
 
export const EXAMPLE_VEHICLES_DATA: Vehicle[] = [
  { id: 1, brand: 'Tesla', fuel: 'electric' },
  { id: 2, brand: 'BMW', fuel: 'diesel' },
  { id: 3, brand: 'Audi', fuel: 'gasoline' },
  { id: 4, brand: 'Mercedes', fuel: 'diesel' },
  { id: 5, brand: 'Toyota', fuel: 'hybrid' },
  { id: 6, brand: 'Volkswagen', fuel: 'gasoline' },
  { id: 7, brand: 'Hyundai', fuel: 'electric' },
  { id: 8, brand: 'Ford', fuel: 'diesel' },
  { id: 9, brand: 'Honda', fuel: 'hybrid' },
  { id: 10, brand: 'Volvo', fuel: 'electric' },
  { id: 11, brand: 'Porsche', fuel: 'gasoline' },
  { id: 12, brand: 'Kia', fuel: 'electric' },
  { id: 13, brand: 'Mazda', fuel: 'gasoline' },
  { id: 14, brand: 'Nissan', fuel: 'electric' },
  { id: 15, brand: 'Renault', fuel: 'diesel' },
  { id: 16, brand: 'Peugeot', fuel: 'hybrid' },
  { id: 17, brand: 'Skoda', fuel: 'diesel' },
  { id: 18, brand: 'Fiat', fuel: 'gasoline' },
  { id: 19, brand: 'Opel', fuel: 'diesel' },
  { id: 20, brand: 'Dacia', fuel: 'lpg' },
  { id: 21, brand: 'Lexus', fuel: 'hybrid' },
  { id: 22, brand: 'Land Rover', fuel: 'diesel' },
  { id: 23, brand: 'Jaguar', fuel: 'electric' },
  { id: 24, brand: 'Subaru', fuel: 'gasoline' },
  { id: 25, brand: 'Mitsubishi', fuel: 'hybrid' },
  { id: 26, brand: 'Chevrolet', fuel: 'gasoline' },
  { id: 27, brand: 'Jeep', fuel: 'diesel' },
  { id: 28, brand: 'Suzuki', fuel: 'hybrid' },
  { id: 29, brand: 'Alfa Romeo', fuel: 'gasoline' },
  { id: 30, brand: 'Cupra', fuel: 'electric' }
];
